### ISSUE TITLE
postcss-zindex removes !important

### ISSUE THREAD

**Issue by gsuhajda** [ben-eb/postcss-zindex#5]
while optimising the value of z-indexes, postcss seemingly also removes !important declarations from the css, which causes trouble in our project. (another solution would be to disable postcss-zindex in vueify's cssnano, but there's no option to that yet, see https://github.com/vuejs/vueify/issues/65)

**Comment by ben-eb** [comment]
Can you send me something that I can reproduce this with? cssnano doesn't explicitly look for `!important` declarations to remove them, as you can see we also test this case here:

https://github.com/ben-eb/postcss-zindex/blob/master/test.js#L23-L25

**Comment by gsuhajda** [comment]
I had another deeper look and it seems that the problem is caused by another custom postcss plugin, which adds !important to every declaration. it did so in a wrong way, which was fine for everything else, but interfered with postcss-zindex. sorry for the false alarm!

**Comment by ben-eb** [comment]
:+1:
